package com.wildmare.wmorder.gui.session;
public enum MenuType { BROWSER, MY_ORDERS, HISTORY, COLLECTION, CREATE, CREATE_ITEM_BROWSER, DETAILS, CONFIRM_CREATE, CONFIRM_FULFILL, CONFIRM_CANCEL, ADMIN_INSPECT }
